apiVersion: batch/v1
kind: Job
metadata:
  name: ai-training-cpu
spec:
  template:
    spec:
      containers:
      - name: ai-trainer
        image: tensorflow/tensorflow:latest  # CPU version of TensorFlow
        command: ["python", "-c"]
        args:
          - |
            import tensorflow as tf
            import numpy as np
            # Dummy dataset
            X = np.array([[1], [2], [3], [4]], dtype=np.float32)
            y = np.array([[2], [4], [6], [8]], dtype=np.float32)
            # Model definition
            model = tf.keras.Sequential([tf.keras.layers.Dense(units=1, input_shape=[1])])
            model.compile(optimizer='sgd', loss='mean_squared_error')
            # Training
            model.fit(X, y, epochs=500, verbose=0)
            print("Training complete.")
      restartPolicy: Never

